# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/OpenSSD2/OpenSSD2.bd
# Block Designs: The module: 'OpenSSD2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/OpenSSD2/ip/OpenSSD2_processing_system7_0_0/OpenSSD2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_processing_system7_0_0 || ORIG_REF_NAME==OpenSSD2_processing_system7_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_0_0/OpenSSD2_V2NFC100DDR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_V2NFC100DDR_0_0 || ORIG_REF_NAME==OpenSSD2_V2NFC100DDR_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_0_0/src/SDPRAM_9A16x9B16/SDPRAM_9A16x9B16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDPRAM_9A16x9B16 || ORIG_REF_NAME==SDPRAM_9A16x9B16}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_0_0/src/SDPRAM_16A9024X32B4512/SDPRAM_16A9024X32B4512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDPRAM_16A9024X32B4512 || ORIG_REF_NAME==SDPRAM_16A9024X32B4512}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_0_0/src/c_sub/c_sub.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_sub || ORIG_REF_NAME==c_sub}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_interconnect_0_0/OpenSSD2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_interconnect_0_0 || ORIG_REF_NAME==OpenSSD2_axi_interconnect_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_xbar_0/OpenSSD2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_xbar_0 || ORIG_REF_NAME==OpenSSD2_xbar_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_0/OpenSSD2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_0_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_2_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_2_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_3_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_3_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_1_0/OpenSSD2_V2NFC100DDR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_V2NFC100DDR_1_0 || ORIG_REF_NAME==OpenSSD2_V2NFC100DDR_1_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_1_0/src/SDPRAM_9A16x9B16/SDPRAM_9A16x9B16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDPRAM_9A16x9B16 || ORIG_REF_NAME==SDPRAM_9A16x9B16}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_1_0/src/SDPRAM_16A9024X32B4512/SDPRAM_16A9024X32B4512.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDPRAM_16A9024X32B4512 || ORIG_REF_NAME==SDPRAM_16A9024X32B4512}]

# IP: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_1_0/src/c_sub/c_sub.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_sub || ORIG_REF_NAME==c_sub}]

# IP: bd/OpenSSD2/ip/OpenSSD2_clk_wiz_0_0/OpenSSD2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_clk_wiz_0_0 || ORIG_REF_NAME==OpenSSD2_clk_wiz_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_interconnect_0_1/OpenSSD2_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_interconnect_0_1 || ORIG_REF_NAME==OpenSSD2_axi_interconnect_0_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController_0_0/OpenSSD2_NVMeHostController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_NVMeHostController_0_0 || ORIG_REF_NAME==OpenSSD2_NVMeHostController_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController_0_0/src/pcie_7x_0_core_top/pcie_7x_0_core_top.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0_core_top || ORIG_REF_NAME==pcie_7x_0_core_top}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_interconnect_0_2/OpenSSD2_axi_interconnect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_interconnect_0_2 || ORIG_REF_NAME==OpenSSD2_axi_interconnect_0_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_blk_mem_gen_0_0/OpenSSD2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_blk_mem_gen_0_0 || ORIG_REF_NAME==OpenSSD2_blk_mem_gen_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Dispatcher_uCode_0_0/OpenSSD2_Dispatcher_uCode_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_Dispatcher_uCode_0_0 || ORIG_REF_NAME==OpenSSD2_Dispatcher_uCode_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/OpenSSD2_Tiger4NSC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_Tiger4NSC_0_0 || ORIG_REF_NAME==OpenSSD2_Tiger4NSC_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DRSCFIFO288x16WC/DRSCFIFO288x16WC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DRSCFIFO288x16WC || ORIG_REF_NAME==DRSCFIFO288x16WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBDCFIFO64x16DR || ORIG_REF_NAME==DPBDCFIFO64x16DR}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBDCFIFO36x16DR || ORIG_REF_NAME==DPBDCFIFO36x16DR}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO40x64WC || ORIG_REF_NAME==DPBSCFIFO40x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO64x64WC || ORIG_REF_NAME==DPBSCFIFO64x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO80x64WC || ORIG_REF_NAME==DPBSCFIFO80x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO128x64WC || ORIG_REF_NAME==DPBSCFIFO128x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DCDPRAM16x1280WC/DCDPRAM16x1280WC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCDPRAM16x1280WC || ORIG_REF_NAME==DCDPRAM16x1280WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/OpenSSD2_Tiger4NSC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_Tiger4NSC_1_0 || ORIG_REF_NAME==OpenSSD2_Tiger4NSC_1_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DRSCFIFO288x16WC/DRSCFIFO288x16WC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DRSCFIFO288x16WC || ORIG_REF_NAME==DRSCFIFO288x16WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBDCFIFO64x16DR || ORIG_REF_NAME==DPBDCFIFO64x16DR}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBDCFIFO36x16DR || ORIG_REF_NAME==DPBDCFIFO36x16DR}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO40x64WC || ORIG_REF_NAME==DPBSCFIFO40x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO64x64WC || ORIG_REF_NAME==DPBSCFIFO64x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO80x64WC || ORIG_REF_NAME==DPBSCFIFO80x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPBSCFIFO128x64WC || ORIG_REF_NAME==DPBSCFIFO128x64WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DCDPRAM16x1280WC/DCDPRAM16x1280WC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCDPRAM16x1280WC || ORIG_REF_NAME==DCDPRAM16x1280WC}]

# IP: bd/OpenSSD2/ip/OpenSSD2_Tiger4SharedKES_0_0/OpenSSD2_Tiger4SharedKES_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_Tiger4SharedKES_0_0 || ORIG_REF_NAME==OpenSSD2_Tiger4SharedKES_0_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_axi_interconnect_0_3/OpenSSD2_axi_interconnect_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_axi_interconnect_0_3 || ORIG_REF_NAME==OpenSSD2_axi_interconnect_0_3}]

# IP: bd/OpenSSD2/ip/OpenSSD2_xbar_1/OpenSSD2_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_xbar_1 || ORIG_REF_NAME==OpenSSD2_xbar_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_s00_regslice_0/OpenSSD2_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_s00_regslice_0 || ORIG_REF_NAME==OpenSSD2_s00_regslice_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_s01_regslice_0/OpenSSD2_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_s01_regslice_0 || ORIG_REF_NAME==OpenSSD2_s01_regslice_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_m00_data_fifo_0/OpenSSD2_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_m00_data_fifo_0 || ORIG_REF_NAME==OpenSSD2_m00_data_fifo_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_m00_regslice_0/OpenSSD2_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_m00_regslice_0 || ORIG_REF_NAME==OpenSSD2_m00_regslice_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_0/OpenSSD2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_0 || ORIG_REF_NAME==OpenSSD2_auto_pc_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_1/OpenSSD2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_1 || ORIG_REF_NAME==OpenSSD2_auto_pc_1}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_2/OpenSSD2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_2 || ORIG_REF_NAME==OpenSSD2_auto_pc_2}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_pc_3/OpenSSD2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_pc_3 || ORIG_REF_NAME==OpenSSD2_auto_pc_3}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_us_cc_df_0/OpenSSD2_auto_us_cc_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_cc_df_0 || ORIG_REF_NAME==OpenSSD2_auto_us_cc_df_0}]

# IP: bd/OpenSSD2/ip/OpenSSD2_auto_us_cc_df_1/OpenSSD2_auto_us_cc_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_cc_df_1 || ORIG_REF_NAME==OpenSSD2_auto_us_cc_df_1}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_processing_system7_0_0/OpenSSD2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_processing_system7_0_0 || ORIG_REF_NAME==OpenSSD2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_0_0/src/SDPRAM_9A16x9B16/SDPRAM_9A16x9B16_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_0_0/src/SDPRAM_16A9024X32B4512/SDPRAM_16A9024X32B4512_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_xbar_0/OpenSSD2_xbar_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_0/OpenSSD2_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_0_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_0_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_0/OpenSSD2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_0_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_0_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_0_0/OpenSSD2_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_2_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_2_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_2_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_2_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_2_0/OpenSSD2_proc_sys_reset_2_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_3_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_3_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OpenSSD2_proc_sys_reset_3_0 || ORIG_REF_NAME==OpenSSD2_proc_sys_reset_3_0}]

# XDC: bd/OpenSSD2/ip/OpenSSD2_proc_sys_reset_3_0/OpenSSD2_proc_sys_reset_3_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_1_0/src/SDPRAM_9A16x9B16/SDPRAM_9A16x9B16_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_V2NFC100DDR_1_0/src/SDPRAM_16A9024X32B4512/SDPRAM_16A9024X32B4512_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_clk_wiz_0_0/OpenSSD2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_clk_wiz_0_0 || ORIG_REF_NAME==OpenSSD2_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_clk_wiz_0_0/OpenSSD2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_clk_wiz_0_0 || ORIG_REF_NAME==OpenSSD2_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_clk_wiz_0_0/OpenSSD2_clk_wiz_0_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController_0_0/src/pcie_7x_0_core_top/source/pcie_7x_0_core_top-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_core_top || ORIG_REF_NAME==pcie_7x_0_core_top}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_NVMeHostController_0_0/src/pcie_7x_0_core_top/synth/pcie_7x_0_core_top_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_blk_mem_gen_0_0/OpenSSD2_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Dispatcher_uCode_0_0/OpenSSD2_Dispatcher_uCode_0_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DRSCFIFO288x16WC/DRSCFIFO288x16WC/DRSCFIFO288x16WC.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DRSCFIFO288x16WC || ORIG_REF_NAME==DRSCFIFO288x16WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DRSCFIFO288x16WC/DRSCFIFO288x16WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO64x16DR || ORIG_REF_NAME==DPBDCFIFO64x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO64x16DR || ORIG_REF_NAME==DPBDCFIFO64x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO36x16DR || ORIG_REF_NAME==DPBDCFIFO36x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO36x16DR || ORIG_REF_NAME==DPBDCFIFO36x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO40x64WC || ORIG_REF_NAME==DPBSCFIFO40x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO64x64WC || ORIG_REF_NAME==DPBSCFIFO64x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO80x64WC || ORIG_REF_NAME==DPBSCFIFO80x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO128x64WC || ORIG_REF_NAME==DPBSCFIFO128x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_0_0/src/DCDPRAM16x1280WC/DCDPRAM16x1280WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DRSCFIFO288x16WC/DRSCFIFO288x16WC/DRSCFIFO288x16WC.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DRSCFIFO288x16WC || ORIG_REF_NAME==DRSCFIFO288x16WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DRSCFIFO288x16WC/DRSCFIFO288x16WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO64x16DR || ORIG_REF_NAME==DPBDCFIFO64x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO64x16DR || ORIG_REF_NAME==DPBDCFIFO64x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO64x16DR/DPBDCFIFO64x16DR_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO36x16DR || ORIG_REF_NAME==DPBDCFIFO36x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBDCFIFO36x16DR || ORIG_REF_NAME==DPBDCFIFO36x16DR}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBDCFIFO36x16DR/DPBDCFIFO36x16DR_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO40x64WC || ORIG_REF_NAME==DPBSCFIFO40x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO40x64WC/DPBSCFIFO40x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO64x64WC || ORIG_REF_NAME==DPBSCFIFO64x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO64x64WC/DPBSCFIFO64x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO80x64WC || ORIG_REF_NAME==DPBSCFIFO80x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO80x64WC/DPBSCFIFO80x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DPBSCFIFO128x64WC || ORIG_REF_NAME==DPBSCFIFO128x64WC}] {/U0 }]/U0 ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DPBSCFIFO128x64WC/DPBSCFIFO128x64WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_Tiger4NSC_1_0/src/DCDPRAM16x1280WC/DCDPRAM16x1280WC_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_xbar_1/OpenSSD2_xbar_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_s00_regslice_0/OpenSSD2_s00_regslice_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_s01_regslice_0/OpenSSD2_s01_regslice_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_m00_data_fifo_0/OpenSSD2_m00_data_fifo_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_m00_regslice_0/OpenSSD2_m00_regslice_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_0/OpenSSD2_auto_pc_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_1/OpenSSD2_auto_pc_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_2/OpenSSD2_auto_pc_2_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_pc_3/OpenSSD2_auto_pc_3_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_cc_df_0/OpenSSD2_auto_us_cc_df_0_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_cc_df_0/OpenSSD2_auto_us_cc_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_cc_df_0 || ORIG_REF_NAME==OpenSSD2_auto_us_cc_df_0}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_cc_df_1/OpenSSD2_auto_us_cc_df_1_ooc.xdc

# XDC: bd/OpenSSD2/ip/OpenSSD2_auto_us_cc_df_1/OpenSSD2_auto_us_cc_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OpenSSD2_auto_us_cc_df_1 || ORIG_REF_NAME==OpenSSD2_auto_us_cc_df_1}] {/inst }]/inst ]]

# XDC: bd/OpenSSD2/OpenSSD2_ooc.xdc
